### ISSUE TITLE
Don't fail test suite when Saucelabs cannot start a browser istance

### ISSUE THREAD

**Issue by nicolocarpignoli** [Chialab/rna-cli#24]
At the moment, when rna runs unit tests on saucelabs, if saucelabs systems are not able to start a browser, the entire suite fails.

It's better for real use cases to skip such browser(s) and let the suite continue.

**Comment by edoardocavazza** [comment]
Maybe is related with https://github.com/admc/wd/issues/520

**Comment by edoardocavazza** [comment]
Waiting for this PR: https://github.com/admc/wd/pull/522

**Comment by edoardocavazza** [comment]
And this: https://github.com/karma-runner/karma-sauce-launcher/pull/148
