### ISSUE TITLE
Remove the warning of not having latest version after upgrading to it

### ISSUE THREAD

**Issue by nicolocarpignoli** [Chialab/rna-cli#56]
There's a bug on RNA CLI that shows a warning that invites to download the latest version of the cli even if last launched command was the upgrade command.

**Comment by edoardocavazza** [comment]
We could completely refactor the check update using https://www.npmjs.com/package/update-notifier

**Comment by nicolocarpignoli** [comment]
Seems cleaner, nice idea

**Comment by nicolocarpignoli** [comment]
I looked into `update-notifier` and it works different from rna-cli actual update-checker.

`update-notifier`, after the initialization, spawns an update alert after a specified interval. This could be useful and we could add this new way instead of the current. At that point, I think that `rna upgrade` command can be deprecated. We can only use update-notifier with a low interval (like 2-3 hours) and let it spawn the alert for us. If somebody wants to force the upgrade it can be done with yarn add.

**Comment by nicolocarpignoli** [comment]
looking at https://github.com/Chialab/rna-cli/tree/2.0.0 I see that `upgrade` command is deprecated, so it makes sense to use `update-notifier` with the 'standard' usage.

**Comment by nicolocarpignoli** [comment]
obsolete after version 2.0.0
